DROP TABLE IF EXISTS "application_labels";
CREATE TABLE "application_labels" ("application_labels_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "tag" TEXT, "value" TEXT, "default_value" TEXT);
INSERT INTO "application_labels" VALUES(1,'APPLICATION_TITLE','Prem Aangan Manager','Prem Aangan Manager');
INSERT INTO "application_labels" VALUES(2,'BACK','Back','Back');
INSERT INTO "application_labels" VALUES(3,'MENU_HOME','Home','Home');
INSERT INTO "application_labels" VALUES(4,'MENU_BROWSE','Browse','Browse');
INSERT INTO "application_labels" VALUES(5,'MENU_ADD','Add','Add');
INSERT INTO "application_labels" VALUES(6,'MENU_SEARCH','Search','Search');
INSERT INTO "application_labels" VALUES(7,'MENU_SETTINGS','Settings','Settings');
INSERT INTO "application_labels" VALUES(8,'HEADER_TITLE','Welcome to Prem Aangan Manager','Welcome to Prem Aangan Manager');
INSERT INTO "application_labels" VALUES(9,'HEADER_LOGOUT','Logout','Logout');
INSERT INTO "application_labels" VALUES(10,'HEADER_SWITCH_ADMIN','Switch Admin','Switch Admin');
INSERT INTO "application_labels" VALUES(11,'LOGIN_GUEST_ADMIN_TITLE','Prem Aangan Manager','Prem Aangan Manager');
INSERT INTO "application_labels" VALUES(12,'LOGIN_GUEST_ADMIN_SUBTITLE','Login to start','Login to start');
INSERT INTO "application_labels" VALUES(11,'LOGIN_ADMIN_TITLE','Prem Aangan Manager','Prem Aangan Manager');
INSERT INTO "application_labels" VALUES(13,'LOGIN_ADMIN_SUBTITLE','Select one Admin to start','Select one Admin to start');
INSERT INTO "application_labels" VALUES(14,'LOGIN_HELP1','Please click on one of the options to begin','Please click on one of the options to begin');
INSERT INTO "application_labels" VALUES(15,'LOGIN_HELP2','Please select one admin and enter password to login','Please select one admin and enter password to login');
INSERT INTO "application_labels" VALUES(16,'LOGIN_ERROR1','Password Incorrect','Password Incorrect');
INSERT INTO "application_labels" VALUES(17,'GUEST','Guest','Guest');
INSERT INTO "application_labels" VALUES(18,'ADMIN','Admin','Admin');
INSERT INTO "application_labels" VALUES(19,'ADMIN1','Admin1','Admin1');
INSERT INTO "application_labels" VALUES(20,'ADMIN2','Admin2','Admin2');
INSERT INTO "application_labels" VALUES(21,'ADMIN3','Admin3','Admin3');
INSERT INTO "application_labels" VALUES(22,'PASSWORD','Password','Password');
INSERT INTO "application_labels" VALUES(23,'PASSWORD_PROMPT','Enter Password','Enter Password');
INSERT INTO "application_labels" VALUES(24,'LOGIN','Login','Login');
INSERT INTO "application_labels" VALUES(25,'HOME_TITLE','Prem Aangan','Prem Aangan');
INSERT INTO "application_labels" VALUES(26,'HOME_SUBTITLE1','A new hope for a new tomorrow','A new hope for a new tomorrow');
INSERT INTO "application_labels" VALUES(27,'HOME_SUBTITLE2','Our Vision','Our Vision');
INSERT INTO "application_labels" VALUES(28,'HOME_SUBTITLE3','To uplift and empower the underprivileged of our society, to lead a better quality life','To uplift and empower the underprivileged of our society, to lead a better quality life');
INSERT INTO "application_labels" VALUES(29,'HOME_ABOUT_THIS_SOFTWARE','About this Software','About this Software');
